### ISSUE TITLE
Moving gpu burn to meta tegra

### ISSUE THREAD

**Issue by shlomow** [madisongh/test-distro#4]
Hi!

I think that the gpu burn can be in meta tegra. What do you think? Is it okay if I send a patch?

**Comment by madisongh** [comment]
It probably needs some updating - I forked off the original code quite a while ago, and haven't looked back to see if it's been upgraded to use newer APIs rather than the ones being flagged as deprecated now.

But yeah, I guess it would be OK to move to meta-tegra, or maybe meta-tegra/contrib.
